---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 40eae4ef1109d880c1e5b885a5bfddd6c784cbea
    fabric8.io/git-branch: master
    fabric8.io/scm-con-url: scm:git:git@github.com:wolsnut4/easydebt-platform.git/apps/keycloak-db
    fabric8.io/scm-devcon-url: scm:git:git@github.com:wolsnut4/easydebt-platform.git/apps/keycloak-db
    fabric8.io/scm-tag: app-console-2.0.1
    fabric8.io/scm-url: http://github.com/wolsnut4/easydebt-platform/apps/keycloak-db
  labels:
    service: keycloak-db
    app: keycloak-db
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: io.clarksnut.platform.apps
  name: keycloak-db
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    service: keycloak-db
    app: keycloak-db
    provider: fabric8
    group: io.clarksnut.platform.apps
  type: ClusterIP
