---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: keycloak
    fabric8.io/target-platform: kubernetes
    fabric8.io/git-commit: c0a681b2565e7710e8adb7f7ddd9ce4bcc0f037a
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=keycloak&var-version=1.0-SNAPSHOT
    fabric8.io/scm-con-url: scm:git:git@github.com:clarksnut/clarksnut-platform.git/apps/keycloak
    fabric8.io/scm-url: http://github.com/clarksnut/clarksnut-platform/apps/keycloak
    fabric8.io/git-branch: master
    fabric8.io/scm-devcon-url: scm:git:git@github.com:clarksnut/clarksnut-platform.git/apps/keycloak
    fabric8.io/scm-tag: app-console-2.0.1
  labels:
    app: keycloak
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: io.clarksnut.platform.apps
  name: keycloak
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: keycloak
      provider: fabric8
      group: io.clarksnut.platform.apps
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: c0a681b2565e7710e8adb7f7ddd9ce4bcc0f037a
        pod.beta.kubernetes.io/init-containers: |-
          [
          {
            "name": "envvar-substitution",
            "image": "fabric8/envsubst-file:1.0.0",
            "imagePullPolicy": "IfNotPresent",
            "args": [
              "clarksnut-realm.json"
            ],
            "env": [{
              "name": "AUTH_URL",
              "valueFrom": {
                      "configMapKeyRef": {
                          "name": "keycloak",
                          "key": "auth.api.url"
                      }
                  }
            },
            {
              "name": "CLARKSNUT_URL",
              "valueFrom": {
                      "configMapKeyRef": {
                          "name": "keycloak",
                          "key": "clarksnut.api.url"
                      }
                  }
            },
            {
              "name": "JENKINS_URL",
              "valueFrom": {
                      "configMapKeyRef": {
                          "name": "keycloak",
                          "key": "jenkins.url"
                      }
                  }
            },
            {
              "name": "KEYCLOAK_URL",
              "valueFrom": {
                      "configMapKeyRef": {
                          "name": "keycloak",
                          "key": "keycloak.url"
                      }
                  }
            },
            {
              "name": "CLARKSNUTUI_URL",
              "valueFrom": {
                      "configMapKeyRef": {
                          "name": "keycloak",
                          "key": "clarksnutui.url"
                      }
                  }
            },
            {
              "name": "KEYCLOAK_PRIVATEKEY",
              "valueFrom": {
                      "secretKeyRef": {
                          "name": "keycloak",
                          "key": "kc.private.key"
                      }
                  }
            },
            {
              "name": "KEYCLOAK_PUBLICKEY",
              "valueFrom": {
                      "secretKeyRef": {
                          "name": "keycloak",
                          "key": "kc.public.key"
                      }
                  }
            },
            {
              "name": "KEYCLOAK_CLIENTID_SECRET",
              "valueFrom": {
                      "secretKeyRef": {
                          "name": "keycloak",
                          "key": "kc.clientid.secret"
                      }
                  }
            },
            {
              "name": "K8S_API_SERVER",
              "valueFrom": {
                      "configMapKeyRef": {
                          "name": "keycloak",
                          "key": "apiserver.url"
                      }
                  }
            },
            {
              "name": "HIDE_OPENSHIFT_BTN",
              "value": "true"
            },
            {
              "name": "HIDE_GITHUB_BTN",
              "value": "false"
            }],
            "volumeMounts": [
            {
              "name": "keycloak-config",
              "mountPath": "/workdir/clarksnut-realm.json",
              "subPath": "config/clarksnut-realm.json"
            },
            {
              "name": "keycloak-subst-config",
              "mountPath": "/processed"
            }
            ]
          },
          {
              "name": "init-dependencyservice",
              "image": "fabric8/fabric8-dependency-wait-service:v6632df1",
              "imagePullPolicy": "IfNotPresent",
              "command": ["sh", "-c", "fabric8-dependency-wait-service-linux-amd64 postgres://keycloak@keycloak-db:5432"],
              "env": [{
                "name": "DEPENDENCY_POLL_INTERVAL",
                "value": "1"
              }, {
                "name": "DEPENDENCY_LOG_VERBOSE",
                "value": "true"
              }]
          }]
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=keycloak&var-version=1.0-SNAPSHOT
        fabric8.io/scm-con-url: scm:git:git@github.com:clarksnut/clarksnut-platform.git/apps/keycloak
        fabric8.io/scm-url: http://github.com/clarksnut/clarksnut-platform/apps/keycloak
        configmap.fabric8.io/update-on-change: keycloak
        fabric8.io/target-platform: kubernetes
        fabric8.io/git-branch: master
        fabric8.io/scm-devcon-url: scm:git:git@github.com:clarksnut/clarksnut-platform.git/apps/keycloak
        fabric8.io/scm-tag: app-console-2.0.1
        maven.fabric8.io/source-url: jar:file:/home/admin/git/clarksnut-platform/apps/keycloak/target/keycloak-1.0-SNAPSHOT.jar!/META-INF/fabric8/kubernetes.yml
      labels:
        app: keycloak
        provider: fabric8
        version: 1.0-SNAPSHOT
        group: io.clarksnut.platform.apps
    spec:
      containers:
      - args:
        - -b $(INTERNAL_POD_IP)
        - -Djgroups.bind_addr=global
        - -Djboss.node.name=$(INTERNAL_POD_IP)
        - -Dkeycloak.migration.action=import
        - -Dkeycloak.migration.provider=singleFile
        - -Dkeycloak.migration.file=/opt/jboss/keycloak/standalone/configuration/import/clarksnut-realm.json
        - -Dkeycloak.migration.strategy=IGNORE_EXISTING
        env:
        - name: POSTGRES_HOSTNAME
          value: keycloak-db
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: keycloak
        - name: OPERATING_MODE
          value: standalone
        - name: POSTGRES_PORT_5432_TCP_ADDR
          value: keycloak-db
        - name: INTERNAL_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              key: kc.user
              name: keycloak
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kc.password
              name: keycloak
        - name: KEYCLOAK_CLIENTID_SECRET
          valueFrom:
            secretKeyRef:
              key: kc.clientid.secret
              name: keycloak
        - name: KEYCLOAK_PRIVATEKEY
          valueFrom:
            secretKeyRef:
              key: kc.private.key
              name: keycloak
        - name: KEYCLOAK_PUBLICKEY
          valueFrom:
            secretKeyRef:
              key: kc.public.key
              name: keycloak
        - name: HIDE_GOOGLE_BTN
          value: "false"
        image: fabric8/keycloak-postgres:v15751c8
        livenessProbe:
          httpGet:
            path: /auth
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
        name: keycloak
        readinessProbe:
          httpGet:
            path: /auth
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/standalone/configuration/import
          name: keycloak-subst-config
        - mountPath: /opt/jboss/keycloak/themes/clarksnut
          name: keycloak-theme
      volumes:
      - emptyDir: {}
        name: keycloak-subst-config
      - configMap:
          items:
          - key: clarksnut-realm.json
            path: config/clarksnut-realm.json
          name: keycloak
        name: keycloak-config
      - gitRepo:
          directory: login
          repository: https://github.com/clarksnut/clarksnut-keycloak-theme.git
        name: keycloak-theme
